# Generated by Django 6.0.2 on 2026-02-10 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionProductos', '0003_alter_producto_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
