# Generated by Django 6.0.2 on 2026-02-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionProductos', '0007_alter_comentario_comentario_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.BooleanField(default=0),
        ),
    ]
